name: Build and release Systemd sysext images
on:
  push:
    tags:
      - '202[4-9].[0-1][0-9].[0-3][0-9].[0-9]+'
jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      # allow the action to create a release
      contents: write
    steps:
      # checkout the sources
      - uses: actions/checkout@v4
        with:
          path: bakery

      # prepare build host
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: install prerequisites
        run: |
          set -euxo pipefail

          sudo apt update -qq && sudo apt install -yqq \
            curl \
            jq \
            squashfs-tools \
            xz-utils \
            gawk

      - name: build release artifacts
        run: |
          pushd bakery
          REPO=${{ github.repository }} ./tag_build.sh

      - name: create a new release with some artifacts
        uses: softprops/action-gh-release@v2
        with:
          make_latest: false
          body_path: bakery/Release.md
          files: |
            bakery/SHA256SUMS
            bakery/*.raw
            bakery/*.conf
